utest: Prefix uint32_t with rt_
mipssim bsp failed to build because missing rt_ prefix.

/**/rt-thread/components/utilities/utest/utest.h:53:5: error: unknown type name 'uint32_t'
     uint32_t passed_num;
     ^
/**/rt-thread/components/utilities/utest/utest.h:54:5: error: unknown type name 'uint32_t

Signed-off-by: Jiaxun Yang <jiaxun.yang@flygoat.com>